name: Swift

on:
  push:
    branches: [master/6.0]
  pull_request:
    branches: [master/6.0]

jobs:
  test:
    container:
      image: vapor/swift:5.2-xenial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build -v
      - name: Start MongoDB v${{ matrix.mongodb-version }}
      uses: superchargejs/mongodb-github-action@1.1.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
      - name: Run tests
        run: swift test -v
